### ISSUE TITLE
Curriculum Pre-Requisite data mis entry

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/cict-student-evaluation-system#12]
- ACT 15-16 with ID of **15**
- ACT 15-16 rev2 with ID of **17**

the student in the sample has a complete grade for first year
![error1](https://user-images.githubusercontent.com/30278929/34076913-01615380-e32f-11e7-940b-d3e013a20557.PNG)

How come that there is a subject not for encoding ?
![error2](https://user-images.githubusercontent.com/30278929/34076916-0f76f16e-e32f-11e7-8079-031ddd0d2fbd.PNG)

The subject that is not for encoding is **ACT 293 ID 428**
where in curriculum **15** the pre requisite is **ACT 163 with SUBJECT_ID 475**
where in curriculum **17 the REV 2** the pre requisite is **ACT 163 with SUBJECT_ID 419**

How come that the pre requisite of **ACT 293 ID 428** in both curriculum 15 and 17 are the same
![error4](https://user-images.githubusercontent.com/30278929/34076936-b781ca1e-e32f-11e7-803d-e13ecbf5168c.PNG)

this is a **HIGH PRIORITY** bug that the subject from other curriculum was able to be added as a pre requisite in another curriculum

These are the subjects:
![error6](https://user-images.githubusercontent.com/30278929/34076942-e1e042d6-e32f-11e7-9cbf-a46b08239ee1.PNG)

Summary
**CURRICULUM 15** -> **ACT 293 ID 428** Requires **ACT 163 with SUBJECT_ID 475** but the subject assigned was from another curriculum **CURRICULUM 17** -> **ACT 163 with SUBJECT_ID 419**

**Comment by jhmvin** [comment]
![image](https://user-images.githubusercontent.com/30278929/34076971-0b4a1b82-e331-11e7-9c44-5f68bd6cb547.png)



![image](https://user-images.githubusercontent.com/30278929/34076974-26191ac6-e331-11e7-85ab-5a00b19d29ca.png)


Please supply necessary fields to provide more identification and other fields to properly distinguish differences between subjects

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/34077137-3e0e8e90-e336-11e7-94a2-032474326111.png)
this just happened when i commented this part of the system just to fix the mistaken inputs on the curriculum and i assure that this will never gonna happen again lol
