### ISSUE TITLE
Incorrect Pre requisite or missing

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/cict-student-evaluation-system#16]
ACT 15-16 (OLD)
- ACT 163
- ACT 223

ACT 15-16 REV 2 (NEW)
- ACT 163
- ACT 213 **missing ACT 143 pre requisite**
- ACT 223 ** missing ACT 143 pre requisite**
- ACT 263

use the database backup where the curriculum is not yet implemented then fix this issues

**Comment by joemardc98** [comment]
![image](https://user-images.githubusercontent.com/33676664/34136023-d7163976-e49e-11e7-95ef-a92000ee42a7.png)
this missing prereq are those subjects that I consider as co-requisite because they are in the same year and semester. I already told u bout that.
