### ISSUE TITLE
System Generated Reports (NOT ISO)

### ISSUE THREAD

**Issue by jhmvin** [jhmvin/cict-student-evaluation-system#5]
- allow to change their headers during printing or create a setting in report window which will consist only of report headers and description where they will appear
e.g. Misstatement - this  report is generated ..... in ..there .. that shows... number of misstated evaluation
just like in the system values but here put a brief description on what does the field does
use the system values table

- hide or show requested columns

**Comment by joemardc98** [comment]
done
